Price lookup refactor
tender-finance/tender-frontend pull request #89
Opened 2022-05-24 16:03 UTC by johnmosesman

Move price onto token and calculate it once when creating the token pairs so we don’t have to re-calculate it a bunch of times

2022-05-24 16:04 UTC, johnmosesman commented on app/hooks/use-markets.ts
> +  signer: JsonRpcSigner | null | undefined,
Signer is now used at the context top level so it can just be passed in here instead of called directly

2022-05-24 16:05 UTC, johnmosesman commented on app/hooks/use-tender-context.ts
> +import { useWeb3Signer } from "./use-web3-signer";
Signer needs to be at the top level now and passed in to two places

2022-05-24 16:06 UTC, johnmosesman commented on app/hooks/use-token-pairs.ts
> +    },
Load the price one time and put it on the token data

2022-05-24 16:07 UTC, johnmosesman commented on app/hooks/use-token-pairs.ts
> +  }, [signer, onSupportedNetwork, networkData]);
Pass through signer to get the price

2022-05-24 16:40 UTC, mitchtrale commented on app/hooks/use-markets.ts
> +  signer: JsonRpcSigner | null | undefined,
cool

2022-05-24 16:46 UTC, mitchtrale requested changes
seems good once the eslint stuff is fixed up

2022-05-25 18:56 UTC, johnmosesman commented
I still need to break out the Token type into a ConfigToken or something before we can merge

2022-05-26 17:04 UTC, johnmosesman commented on app/hooks/use-token-pairs.ts
> +  let token: TokenConfig = networkData.Tokens[symbol];
After adding the `priceInUsd` property to `Token` type it no longer matches the token in the config data, so it needs a new type.

2022-05-26 17:05 UTC, johnmosesman commented on app/types/global.ts
>  }
After adding `priceInUsd` to token it no longer matches against the config data so it needs a new type. Currently lots of duplication but this could diverge more over time.

2022-05-26 17:11 UTC, ryanlabouve commented on app/types/global.ts
>  export interface Token {
since this is an additive type, you should use union to combine TokenConfig and Token instead of retyping. 

Think it's like ```
Token & {
    extraTypes: string;
}
```

2022-05-26 17:12 UTC, ryanlabouve approved these changes
LGTM % comment

2022-05-26 18:39 UTC, johnmosesman commented on app/types/global.ts
>  export interface Token {
noice

2022-05-26 18:46 UTC, mitchtrale approved these changes

2022-05-26 18:51 UTC, merged